=== iesgrancapitan-llmm/mi-primera-pagina-web-JPradillo/T5/T5-2/Actividad5/Factura.dtd
<!ELEMENT Factura (cabecera, apunte+)>
<!ELEMENT cabecera (fecha, cliente)>
<!ATTLIST cabecera factura_id NMTOKEN #REQUIRED>
<!ELEMENT fecha ((dia, mes, anno) | (mes, dia, anno))>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT anno (#PCDATA)>
<!ELEMENT cliente (direccion)>
<!ATTLIST cliente cliente_id ID #REQUIRED
                  nombre CDATA #IMPLIED
                  telefono NMTOKEN #IMPLIED>
<!ELEMENT direccion (nombre_via, numero, localidad, provincia, cp, pais?)>
<!ELEMENT nombre_via (#PCDATA)>
<!ATTLIST nombre_via tipovia (Calle | Avda | Plaza | Carretera) "Calle">
<!ELEMENT numero (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT apunte (concepto)>
<!ATTLIST apunte descuento (promocion | regular) "regular"
                 precio CDATA #REQUIRED
                 moneda CDATA #FIXED "euro">
<!ELEMENT concepto (#PCDATA)>
<!ATTLIST concepto cantidad NMTOKEN #IMPLIED>

=== iesgrancapitan-llmm/mi-primera-pagina-web-JPradillo/T5/T5-2/Actividad5/Factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Factura SYSTEM "./Factura.dtd">
<!-- <!DOCTYPE Factura [
<!ELEMENT Factura (cabecera, apunte+)>
<!ELEMENT cabecera (fecha, cliente)>
<!ATTLIST cabecera factura_id NMTOKEN #REQUIRED>
<!ELEMENT fecha ((dia, mes, anno) | (mes, dia, anno))>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT anno (#PCDATA)>
<!ELEMENT cliente (direccion)>
<!ATTLIST cliente cliente_id ID #REQUIRED
                  nombre CDATA #IMPLIED
                  telefono NMTOKEN #IMPLIED>
<!ELEMENT direccion (nombre_via, numero, localidad, provincia, cp, pais?)>
<!ELEMENT nombre_via (#PCDATA)>
<!ATTLIST nombre_via tipovia (Calle | Avda | Plaza | Carretera) "Calle">
<!ELEMENT numero (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT apunte (concepto)>
<!ATTLIST apunte descuento (promocion | regular) "regular"
                 precio CDATA #REQUIRED
                 moneda CDATA #FIXED "euro">
<!ELEMENT concepto (#PCDATA)>
<!ATTLIST concepto cantidad NMTOKEN #IMPLIED>
]> -->
<Factura>
    <cabecera factura_id="12345">
        <fecha>      
            <mes>Marzo</mes>
            <dia>15</dia>
            <anno>2021</anno>
        </fecha> 
        <cliente cliente_id="J-123" nombre="Juan García Sánchez" telefono="957-000-111">
            <direccion> 
                <nombre_via tipovia="Calle">Fragua</nombre_via>
                <numero>6</numero>
                <localidad>Fernán Núñez</localidad>
                <provincia>Córdoba</provincia>
                <cp>14550</cp>
                <pais>España</pais>
            </direccion>
        </cliente>
    </cabecera>
    <apunte descuento="promocion" precio="57">
        <concepto cantidad="2">Tarjeta gráfica 3D</concepto>
    </apunte>
    <apunte moneda="euro" precio="27,5">
        <concepto>Memoria Flash</concepto>
    </apunte>
</Factura>
