=== iesgrancapitan-llmm/mi-primera-pagina-web-JPradillo/T5/T5-2/Ejercicio11/Liga1/Liga_Futbol.dtd
<!ELEMENT liga (equipos+)>
<!ELEMENT equipos (local, visitante, goles_local, goles_visitante)>
<!ELEMENT local (#PCDATA)>
<!ELEMENT visitante (#PCDATA)>
<!ELEMENT goles_local (#PCDATA)>
<!ELEMENT goles_visitante (#PCDATA)>

=== iesgrancapitan-llmm/mi-primera-pagina-web-JPradillo/T5/T5-2/Ejercicio11/Liga1/Liga_Futbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "Liga_Futbol.dtd">
<liga>
    <equipos>
        <local>Nottingham Presa</local>
        <visitante>Inter de Mitente</visitante>
        <goles_local>0</goles_local>
        <goles_visitante>1</goles_visitante>
    </equipos>
    <equipos>
        <local>Vodka Juniors</local>
        <visitante>Sparta da Risa</visitante>
        <goles_local>3</goles_local>
        <goles_visitante>3</goles_visitante>
    </equipos>
    <equipos>
        <local>Water de Munich</local>
        <visitante>Esteaua es del grifo</visitante>
        <goles_local>4</goles_local>
        <goles_visitante>2</goles_visitante>
    </equipos>
</liga>
