<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libro+,prestamo+)>
    <!ELEMENT libro (titulo,autor)>
    <!ATTLIST libro id NMTOKEN #REQUIRED>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT prestamo (fecha)>
    <!ATTLIST prestamo idref NMTOKEN #REQUIRED>
    <!ELEMENT fecha (#PCDATA)>
]>

<biblioteca>
    <libro id="1234">
        <titulo>1 vida, 2 destinos</titulo>
        <autor>Laura Gallego</autor>
    </libro>
    <prestamo idref="1234">
        <fecha>24/02/2024</fecha>
    </prestamo>
</biblioteca>